### ISSUE TITLE
Device is unavailable

### ISSUE THREAD

**Issue by rodvand** [frodeheg/no.hoiax#1]
I'm currently getting this error using the app:
![image](https://user-images.githubusercontent.com/56864/188961550-7d60c2a3-7878-4c50-940d-7fa2c6a5d08c.png)

I have tried using repair which triggers a new login in the myUplink website. App version is 1.7.8. I have also tried removing the device and adding it again. Controlling the device through the myUplink app works as expected. This is with a Høiax Connected 200. 

Any tips to get this working again?

**Comment by frodeheg** [comment]
Takk for feilrapporten, Høiax har for tiden noen problemer med firmware på de nyeste tankene og i den forbindelse har de gjort mange hyppige endringer i API'et mot myUplink. Dette gjør at appen jeg lagde for Homey kan ha litt trøbbel med å kommunisere med myuplink for tiden. Jeg prøver å imøtekomme endringene så snart som mulig og denne feilmeldingen er en konsekvens av dette. Takk for at du sendte den til meg, skal prøve å se om jeg får lagt ut en ny versjon i kveld.

Du finner forøvrig mer informasjon om de pågående problemene her: https://community.homey.app/t/hoiax-connected-smart-water-heaters/63238

Med vennlig hilsen Frode

**Comment by frodeheg** [comment]
Klarer du forresten å styre berederen fra myUplink? Hvis ikke er det ingenting jeg kan gjøre før Høiax har fikset problemet. Dersom myUplink fortsatt virker for deg så skal jeg nok få orden i sakene relativt raskt.

**Comment by frodeheg** [comment]
Tror det skal være fikset i versjon 1.7.9 som er ute til testing nå. ( https://homey.app/a/no.hoiax/test )

**Comment by rodvand** [comment]
Funka flott med 1.7.9! Takk for en flott app!

**Comment by frodeheg** [comment]
Takk og beklager for trøbbelet, akkurat dette var en slurvefeil fra min side.
