### ISSUE TITLE
Fetcherror during request to myuplink

### ISSUE THREAD

**Issue by jrogde** [frodeheg/no.hoiax#2]
Fetcherror during request to myuplink. 

App version 1.7.10. 

See picture for details
![Screenshot_20220910_052627_app homey](https://user-images.githubusercontent.com/2065217/189467014-de223b0d-7828-4fa2-95b3-031ead32435a.png)

**Comment by frodeheg** [comment]
Hei, fikk noe tilsvarende  selv på fredag som løste seg når jeg trykket på prøv å reparere. Vil tro myuplink gjorde noen endringer, aner ikke helt hva som skjedde. Antar du løste det på omtrent samme måte.
Jeg har ikke opplevd dette før i løpet av de 3 månedene jeg har hatt tanken så antar det ikke er noe som dukker opp igjen med det første. Dersom du ser det igjen og ofte ta kontakt så får jeg se om det er noe jeg kan gjøre for å gjenopprette forbindelsen automatisk (hvis det er mulig).

**Comment by jrogde** [comment]
Hei,

Takk for svar og for en kjempefin homey app 😊.

Ja, jeg har forstått at høiax også gjør en del endringer for tiden og det
kan jo gjøre det utfordrende.

Prøvde å ta repair noen runder uten at det fungerte, men etter et døgn var
den oppe å kjørte igjen.

Jeg lukket issue'et foreløpig, men tar gjerne kontakt igjen dersom jeg får
tilsvarende utfordring igjen.

Mvh Jon Rogde


søn. 11. sep. 2022, 14:03 skrev frodeheg ***@***.***>:
