### ISSUE TITLE
HTTP400 on "Exclude from Homekit"

### ISSUE THREAD

**Issue by trondvh** [frodeheg/no.hoiax#8]
Trying to enable "Exclude from Homekit" under settings returns: 
Failed setting {"undefined":true} due to 400 Bad Request: Failed setting {"undefined":true} due to 400 Bad Request

**Comment by frodeheg** [comment]
The Høiax app will not be maintained because there is a new app that can be used instead. You can beta test it from here:
https://homey.app/a/com.myuplink/test
